version: 2
percy:
  token: web_ca40126d393e3e0a29cdb4b880fbe384e60a26e4a57cc9b1a94623d491c2ddba
snapshot:
  widths:
    - 375
    - 1280
  minHeight: 1024
  percyCSS: ""
  enableJavaScript: false
  cliEnableJavaScript: true
  disableShadowDOM: false
discovery:
  allowedHostnames: []
  disallowedHostnames: []
  networkIdleTimeout: 100
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
  stripExtensions: false
